-- ============================================================================
-- 0035: 여행지 50개 → 100개 확장 (대륙-국가-도시 계층 선택 UI 준비)
-- continent는 별도 컬럼 없이 클라이언트 country_code→대륙 정적 매핑으로 뺀다
-- (countryLookup.ts 패턴과 동일 — 대륙은 자주 안 바뀌는 참조 데이터라 DB 컬럼
-- 유지 비용이 안 맞는다).
-- ============================================================================

insert into public.destinations (slug, country_code, lat, lng, timezone, currency, sort_order) values
  ('chiangmai', 'TH', 18.7883, 98.9853, 'Asia/Bangkok', 'THB', 50),
  ('phuket', 'TH', 7.8804, 98.3923, 'Asia/Bangkok', 'THB', 51),
  ('siemreap', 'KH', 13.3633, 103.8564, 'Asia/Phnom_Penh', 'KHR', 52),
  ('delhi', 'IN', 28.6139, 77.2090, 'Asia/Kolkata', 'INR', 53),
  ('mumbai', 'IN', 19.0760, 72.8777, 'Asia/Kolkata', 'INR', 54),
  ('jaipur', 'IN', 26.9124, 75.7873, 'Asia/Kolkata', 'INR', 55),
  ('kathmandu', 'NP', 27.7172, 85.3240, 'Asia/Kathmandu', 'NPR', 56),
  ('male', 'MV', 4.1755, 73.5093, 'Indian/Maldives', 'MVR', 57),
  ('dubai', 'AE', 25.2048, 55.2708, 'Asia/Dubai', 'AED', 58),
  ('abudhabi', 'AE', 24.4539, 54.3773, 'Asia/Dubai', 'AED', 59),
  ('doha', 'QA', 25.2854, 51.5310, 'Asia/Qatar', 'QAR', 60),
  ('telaviv', 'IL', 32.0853, 34.7818, 'Asia/Jerusalem', 'ILS', 61),
  ('ulaanbaatar', 'MN', 47.8864, 106.9057, 'Asia/Ulaanbaatar', 'MNT', 62),
  ('berlin', 'DE', 52.5200, 13.4050, 'Europe/Berlin', 'EUR', 63),
  ('munich', 'DE', 48.1351, 11.5820, 'Europe/Berlin', 'EUR', 64),
  ('madrid', 'ES', 40.4168, -3.7038, 'Europe/Madrid', 'EUR', 65),
  ('milan', 'IT', 45.4642, 9.1900, 'Europe/Rome', 'EUR', 66),
  ('venice', 'IT', 45.4408, 12.3155, 'Europe/Rome', 'EUR', 67),
  ('florence', 'IT', 43.7696, 11.2558, 'Europe/Rome', 'EUR', 68),
  ('santorini', 'GR', 36.3932, 25.4615, 'Europe/Athens', 'EUR', 69),
  ('athens', 'GR', 37.9838, 23.7275, 'Europe/Athens', 'EUR', 70),
  ('dubrovnik', 'HR', 42.6507, 18.0944, 'Europe/Zagreb', 'EUR', 71),
  ('budapest', 'HU', 47.4979, 19.0402, 'Europe/Budapest', 'HUF', 72),
  ('warsaw', 'PL', 52.2297, 21.0122, 'Europe/Warsaw', 'PLN', 73),
  ('copenhagen', 'DK', 55.6761, 12.5683, 'Europe/Copenhagen', 'DKK', 74),
  ('stockholm', 'SE', 59.3293, 18.0686, 'Europe/Stockholm', 'SEK', 75),
  ('dublin', 'IE', 53.3498, -6.2603, 'Europe/Dublin', 'EUR', 76),
  ('brussels', 'BE', 50.8503, 4.3517, 'Europe/Brussels', 'EUR', 77),
  ('mexicocity', 'MX', 19.4326, -99.1332, 'America/Mexico_City', 'MXN', 78),
  ('cancun', 'MX', 21.1619, -86.8515, 'America/Cancun', 'MXN', 79),
  ('toronto', 'CA', 43.6532, -79.3832, 'America/Toronto', 'CAD', 80),
  ('lasvegas', 'US', 36.1699, -115.1398, 'America/Los_Angeles', 'USD', 81),
  ('miami', 'US', 25.7617, -80.1918, 'America/New_York', 'USD', 82),
  ('havana', 'CU', 23.1136, -82.3666, 'America/Havana', 'CUP', 83),
  ('riodejaneiro', 'BR', -22.9068, -43.1729, 'America/Sao_Paulo', 'BRL', 84),
  ('saopaulo', 'BR', -23.5505, -46.6333, 'America/Sao_Paulo', 'BRL', 85),
  ('buenosaires', 'AR', -34.6037, -58.3816, 'America/Argentina/Buenos_Aires', 'ARS', 86),
  ('lima', 'PE', -12.0464, -77.0428, 'America/Lima', 'PEN', 87),
  ('cusco', 'PE', -13.5320, -71.9675, 'America/Lima', 'PEN', 88),
  ('santiago', 'CL', -33.4489, -70.6693, 'America/Santiago', 'CLP', 89),
  ('capetown', 'ZA', -33.9249, 18.4241, 'Africa/Johannesburg', 'ZAR', 90),
  ('marrakech', 'MA', 31.6295, -7.9811, 'Africa/Casablanca', 'MAD', 91),
  ('cairo', 'EG', 30.0444, 31.2357, 'Africa/Cairo', 'EGP', 92),
  ('nairobi', 'KE', -1.2921, 36.8219, 'Africa/Nairobi', 'KES', 93),
  ('zanzibar', 'TZ', -6.1659, 39.2026, 'Africa/Dar_es_Salaam', 'TZS', 94),
  ('melbourne', 'AU', -37.8136, 144.9631, 'Australia/Melbourne', 'AUD', 95),
  ('brisbane', 'AU', -27.4698, 153.0251, 'Australia/Brisbane', 'AUD', 96),
  ('auckland', 'NZ', -36.8485, 174.7633, 'Pacific/Auckland', 'NZD', 97),
  ('queenstown', 'NZ', -45.0312, 168.6626, 'Pacific/Auckland', 'NZD', 98),
  ('fiji', 'FJ', -17.7134, 178.0650, 'Pacific/Fiji', 'FJD', 99)
on conflict (slug) do nothing;

insert into public.destination_translations (destination_id, locale, name)
select d.id, v.locale, v.name
from (values
  ('chiangmai', 'ko', '치앙마이'), ('chiangmai', 'en', 'Chiang Mai'), ('chiangmai', 'zh-TW', '清邁'), ('chiangmai', 'ja', 'チェンマイ'),
  ('phuket', 'ko', '푸켓'), ('phuket', 'en', 'Phuket'), ('phuket', 'zh-TW', '普吉島'), ('phuket', 'ja', 'プーケット'),
  ('siemreap', 'ko', '시엠레아프'), ('siemreap', 'en', 'Siem Reap'), ('siemreap', 'zh-TW', '暹粒'), ('siemreap', 'ja', 'シェムリアップ'),
  ('delhi', 'ko', '델리'), ('delhi', 'en', 'Delhi'), ('delhi', 'zh-TW', '德里'), ('delhi', 'ja', 'デリー'),
  ('mumbai', 'ko', '뭄바이'), ('mumbai', 'en', 'Mumbai'), ('mumbai', 'zh-TW', '孟買'), ('mumbai', 'ja', 'ムンバイ'),
  ('jaipur', 'ko', '자이푸르'), ('jaipur', 'en', 'Jaipur'), ('jaipur', 'zh-TW', '齋浦爾'), ('jaipur', 'ja', 'ジャイプル'),
  ('kathmandu', 'ko', '카트만두'), ('kathmandu', 'en', 'Kathmandu'), ('kathmandu', 'zh-TW', '加德滿都'), ('kathmandu', 'ja', 'カトマンズ'),
  ('male', 'ko', '말레'), ('male', 'en', 'Malé'), ('male', 'zh-TW', '馬列'), ('male', 'ja', 'マレ'),
  ('dubai', 'ko', '두바이'), ('dubai', 'en', 'Dubai'), ('dubai', 'zh-TW', '杜拜'), ('dubai', 'ja', 'ドバイ'),
  ('abudhabi', 'ko', '아부다비'), ('abudhabi', 'en', 'Abu Dhabi'), ('abudhabi', 'zh-TW', '阿布達比'), ('abudhabi', 'ja', 'アブダビ'),
  ('doha', 'ko', '도하'), ('doha', 'en', 'Doha'), ('doha', 'zh-TW', '杜哈'), ('doha', 'ja', 'ドーハ'),
  ('telaviv', 'ko', '텔아비브'), ('telaviv', 'en', 'Tel Aviv'), ('telaviv', 'zh-TW', '特拉維夫'), ('telaviv', 'ja', 'テルアビブ'),
  ('ulaanbaatar', 'ko', '울란바토르'), ('ulaanbaatar', 'en', 'Ulaanbaatar'), ('ulaanbaatar', 'zh-TW', '烏蘭巴托'), ('ulaanbaatar', 'ja', 'ウランバートル'),
  ('berlin', 'ko', '베를린'), ('berlin', 'en', 'Berlin'), ('berlin', 'zh-TW', '柏林'), ('berlin', 'ja', 'ベルリン'),
  ('munich', 'ko', '뮌헨'), ('munich', 'en', 'Munich'), ('munich', 'zh-TW', '慕尼黑'), ('munich', 'ja', 'ミュンヘン'),
  ('madrid', 'ko', '마드리드'), ('madrid', 'en', 'Madrid'), ('madrid', 'zh-TW', '馬德里'), ('madrid', 'ja', 'マドリード'),
  ('milan', 'ko', '밀라노'), ('milan', 'en', 'Milan'), ('milan', 'zh-TW', '米蘭'), ('milan', 'ja', 'ミラノ'),
  ('venice', 'ko', '베네치아'), ('venice', 'en', 'Venice'), ('venice', 'zh-TW', '威尼斯'), ('venice', 'ja', 'ヴェネツィア'),
  ('florence', 'ko', '피렌체'), ('florence', 'en', 'Florence'), ('florence', 'zh-TW', '佛羅倫斯'), ('florence', 'ja', 'フィレンツェ'),
  ('santorini', 'ko', '산토리니'), ('santorini', 'en', 'Santorini'), ('santorini', 'zh-TW', '聖托里尼'), ('santorini', 'ja', 'サントリーニ島'),
  ('athens', 'ko', '아테네'), ('athens', 'en', 'Athens'), ('athens', 'zh-TW', '雅典'), ('athens', 'ja', 'アテネ'),
  ('dubrovnik', 'ko', '두브로브니크'), ('dubrovnik', 'en', 'Dubrovnik'), ('dubrovnik', 'zh-TW', '杜布羅夫尼克'), ('dubrovnik', 'ja', 'ドゥブロヴニク'),
  ('budapest', 'ko', '부다페스트'), ('budapest', 'en', 'Budapest'), ('budapest', 'zh-TW', '布達佩斯'), ('budapest', 'ja', 'ブダペスト'),
  ('warsaw', 'ko', '바르샤바'), ('warsaw', 'en', 'Warsaw'), ('warsaw', 'zh-TW', '華沙'), ('warsaw', 'ja', 'ワルシャワ'),
  ('copenhagen', 'ko', '코펜하겐'), ('copenhagen', 'en', 'Copenhagen'), ('copenhagen', 'zh-TW', '哥本哈根'), ('copenhagen', 'ja', 'コペンハーゲン'),
  ('stockholm', 'ko', '스톡홀름'), ('stockholm', 'en', 'Stockholm'), ('stockholm', 'zh-TW', '斯德哥爾摩'), ('stockholm', 'ja', 'ストックホルム'),
  ('dublin', 'ko', '더블린'), ('dublin', 'en', 'Dublin'), ('dublin', 'zh-TW', '都柏林'), ('dublin', 'ja', 'ダブリン'),
  ('brussels', 'ko', '브뤼셀'), ('brussels', 'en', 'Brussels'), ('brussels', 'zh-TW', '布魯塞爾'), ('brussels', 'ja', 'ブリュッセル'),
  ('mexicocity', 'ko', '멕시코시티'), ('mexicocity', 'en', 'Mexico City'), ('mexicocity', 'zh-TW', '墨西哥城'), ('mexicocity', 'ja', 'メキシコシティ'),
  ('cancun', 'ko', '칸쿤'), ('cancun', 'en', 'Cancún'), ('cancun', 'zh-TW', '坎昆'), ('cancun', 'ja', 'カンクン'),
  ('toronto', 'ko', '토론토'), ('toronto', 'en', 'Toronto'), ('toronto', 'zh-TW', '多倫多'), ('toronto', 'ja', 'トロント'),
  ('lasvegas', 'ko', '라스베가스'), ('lasvegas', 'en', 'Las Vegas'), ('lasvegas', 'zh-TW', '拉斯維加斯'), ('lasvegas', 'ja', 'ラスベガス'),
  ('miami', 'ko', '마이애미'), ('miami', 'en', 'Miami'), ('miami', 'zh-TW', '邁阿密'), ('miami', 'ja', 'マイアミ'),
  ('havana', 'ko', '아바나'), ('havana', 'en', 'Havana'), ('havana', 'zh-TW', '哈瓦那'), ('havana', 'ja', 'ハバナ'),
  ('riodejaneiro', 'ko', '리우데자네이루'), ('riodejaneiro', 'en', 'Rio de Janeiro'), ('riodejaneiro', 'zh-TW', '里約熱內盧'), ('riodejaneiro', 'ja', 'リオデジャネイロ'),
  ('saopaulo', 'ko', '상파울루'), ('saopaulo', 'en', 'São Paulo'), ('saopaulo', 'zh-TW', '聖保羅'), ('saopaulo', 'ja', 'サンパウロ'),
  ('buenosaires', 'ko', '부에노스아이레스'), ('buenosaires', 'en', 'Buenos Aires'), ('buenosaires', 'zh-TW', '布宜諾斯艾利斯'), ('buenosaires', 'ja', 'ブエノスアイレス'),
  ('lima', 'ko', '리마'), ('lima', 'en', 'Lima'), ('lima', 'zh-TW', '利馬'), ('lima', 'ja', 'リマ'),
  ('cusco', 'ko', '쿠스코'), ('cusco', 'en', 'Cusco'), ('cusco', 'zh-TW', '庫斯科'), ('cusco', 'ja', 'クスコ'),
  ('santiago', 'ko', '산티아고'), ('santiago', 'en', 'Santiago'), ('santiago', 'zh-TW', '聖地牙哥'), ('santiago', 'ja', 'サンティアゴ'),
  ('capetown', 'ko', '케이프타운'), ('capetown', 'en', 'Cape Town'), ('capetown', 'zh-TW', '開普敦'), ('capetown', 'ja', 'ケープタウン'),
  ('marrakech', 'ko', '마라케시'), ('marrakech', 'en', 'Marrakech'), ('marrakech', 'zh-TW', '馬拉喀什'), ('marrakech', 'ja', 'マラケシュ'),
  ('cairo', 'ko', '카이로'), ('cairo', 'en', 'Cairo'), ('cairo', 'zh-TW', '開羅'), ('cairo', 'ja', 'カイロ'),
  ('nairobi', 'ko', '나이로비'), ('nairobi', 'en', 'Nairobi'), ('nairobi', 'zh-TW', '奈洛比'), ('nairobi', 'ja', 'ナイロビ'),
  ('zanzibar', 'ko', '잔지바르'), ('zanzibar', 'en', 'Zanzibar'), ('zanzibar', 'zh-TW', '尚吉巴'), ('zanzibar', 'ja', 'ザンジバル'),
  ('melbourne', 'ko', '멜버른'), ('melbourne', 'en', 'Melbourne'), ('melbourne', 'zh-TW', '墨爾本'), ('melbourne', 'ja', 'メルボルン'),
  ('brisbane', 'ko', '브리즈번'), ('brisbane', 'en', 'Brisbane'), ('brisbane', 'zh-TW', '布里斯本'), ('brisbane', 'ja', 'ブリスベン'),
  ('auckland', 'ko', '오클랜드'), ('auckland', 'en', 'Auckland'), ('auckland', 'zh-TW', '奧克蘭'), ('auckland', 'ja', 'オークランド'),
  ('queenstown', 'ko', '퀸스타운'), ('queenstown', 'en', 'Queenstown'), ('queenstown', 'zh-TW', '皇后鎮'), ('queenstown', 'ja', 'クイーンズタウン'),
  ('fiji', 'ko', '피지'), ('fiji', 'en', 'Fiji'), ('fiji', 'zh-TW', '斐濟'), ('fiji', 'ja', 'フィジー')
) as v(slug, locale, name)
join public.destinations d on d.slug = v.slug
on conflict (destination_id, locale) do update set name = excluded.name;
