-- ============================================================================
-- 0081: 새 도시 200곳 대표 사진 주소 — destinations.cover_url.
-- Storage destination-covers/슬러그.webp(1024x768) + thumbs/슬러그.webp(160x120) 업로드가 끝난 뒤에 적용한다.
-- 이미 값이 있는 도시는 건드리지 않는다(나중에 직접 바꾼 사진 보호).
-- ============================================================================

update public.destinations d
set cover_url = 'https://ifzykfemjzqquyzgpqax.supabase.co/storage/v1/object/public/destination-covers/' || d.slug || '.webp'
where d.cover_url is null
  and d.slug in ('addisababa','adelaide','agra','almaty','amman','antalya','aomori','asahikawa','astana','atlanta','baku','bandarseribegawan','banff','bishkek','bogota','bologna','boston','bratislava','cairns','calgary','cartagena','casablanca','catania','changsha','chengdu','cheongju','chiangrai','chicago','chongqing','christchurch','clark','colombo','coron','daegu','dalat','dalian','dallas','denver','edinburgh','elnido','frankfurt','fuzhou','gdansk','geneva','georgetown','goldcoast','goreme','granada','guangzhou','guilin','gwangju','haikou','haiphong','hakodate','hakone','hallstatt','halong','hamburg','hangzhou','harbin','helsinki','heraklion','himeji','hiroshima','hoian','huahin','hualien','hue','incheon','innsbruck','interlaken','ishigaki','jakarta','johannesburg','johorbahru','kagoshima','kamakura','kanazawa','kandy','karuizawa','kitakyushu','kobe','kochi','koror','kosamui','kotakinabalu','krabi','krakow','kuching','kumamoto','kunming','kurashiki','labuanbajo','langkawi','lijiang','ljubljana','luangprabang','lucerne','luxor','lyon','malacca','malaga','manado','manila','mataram','matsue','matsumoto','matsuyama','miyakojima','miyazaki','monterrey','montreal','muscat','mykonos','nagano','nagasaki','nanjing','naples','nara','nice','niigata','nikko','okayama','orlando','oslo','otaru','palma','panaji','panamacity','papeete','pattaya','perth','phnompenh','phuquoc','pisa','pokhara','portland','portlouis','porto','puertoprincesa','qingdao','quebeccity','reykjavik','rhodes','riga','rovaniemi','saltlakecity','salzburg','samarkand','sandiego','sanya','sapa','seattle','sendai','seville','shenyang','shenzhen','shizuoka','shymkent','split','strasbourg','tagbilaran','taichung','tainan','takamatsu','takayama','tallinn','taoyuan','tashkent','tbilisi','tianjin','tokushima','toyama','troms','ubud','urumqi','valencia','valletta','verona','victoriafalls','vientiane','vilnius','vladivostok','washingtondc','weihai','wellington','wrocaw','wuhan','xiamen','xian','yangon','yanji','yantai','yerevan','yogyakarta','yokohama','yufuin','zagreb','zhangjiajie','zhengzhou');
